name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  coverage:
    name: Test and Publish Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: cp .env.sample .env  
    - uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: e6377f3ac429229d3c7fa4b815d4827f1ed8112a32e4624e9d776acb018f8821
      with:
          coverageCommand: npm run coverage
          # By default, this looks for a `coverage` folder in the root of your project, but you may need to change this
          coverageLocations: './coverage/clover.xml:clover'
          # Great for troubleshooting
          debug: true
