const listings2020 = [
  {
    id: 1,
    title: "Lake Front Dream Escape",
    price: "$98.13",
    landowner_id: 28,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 2,
    title: "Breathtaking Sunrises",
    price: "$112.78",
    landowner_id: 59,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 3,
    title: "Fresh Mountain Air",
    price: "$161.84",
    landowner_id: 25,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 4,
    title: "Towering Forest Brimming with Wild Life",
    price: "$92.17",
    landowner_id: 30,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 5,
    title: "Clifftop Views and Rolling Hills",
    price: "$159.55",
    landowner_id: 28,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 6,
    title: "Cabin Escape Just Above the Clouds",
    price: "$216.31",
    landowner_id: 39,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 7,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$69.33",
    landowner_id: 10,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 8,
    title: "Wilderness Vacation Miles from anyone",
    price: "$169.22",
    landowner_id: 81,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 9,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$218.02",
    landowner_id: 87,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 10,
    title: "Four Wheel Drive Mud Retreat",
    price: "$179.94",
    landowner_id: 15,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 11,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$154.56",
    landowner_id: 17,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 12,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$129.62",
    landowner_id: 69,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 13,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$193.62",
    landowner_id: 76,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 14,
    title: "River Life at its Best",
    price: "$137.42",
    landowner_id: 65,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 15,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$260.39",
    landowner_id: 33,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 16,
    title: "Lake Front Dream Escape",
    price: "$292.22",
    landowner_id: 29,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 17,
    title: "Breathtaking Sunrises",
    price: "$247.49",
    landowner_id: 32,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 18,
    title: "Fresh Mountain Air",
    price: "$260.81",
    landowner_id: 92,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 19,
    title: "Towering Forest Brimming with Wild Life",
    price: "$186.82",
    landowner_id: 66,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 20,
    title: "Clifftop Views and Rolling Hills",
    price: "$105.98",
    landowner_id: 7,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 21,
    title: "Cabin Escape Just Above the Clouds",
    price: "$51.68",
    landowner_id: 83,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 22,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$191.58",
    landowner_id: 93,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 23,
    title: "Wilderness Vacation Miles from anyone",
    price: "$113.23",
    landowner_id: 81,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 24,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$115.96",
    landowner_id: 24,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 25,
    title: "Four Wheel Drive Mud Retreat",
    price: "$147.91",
    landowner_id: 53,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 26,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$127.90",
    landowner_id: 49,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 27,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$257.76",
    landowner_id: 7,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 28,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$215.68",
    landowner_id: 17,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 29,
    title: "River Life at its Best",
    price: "$291.65",
    landowner_id: 62,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 30,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$50.63",
    landowner_id: 73,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 31,
    title: "Lake Front Dream Escape",
    price: "$80.82",
    landowner_id: 12,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 32,
    title: "Breathtaking Sunrises",
    price: "$176.52",
    landowner_id: 71,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 33,
    title: "Fresh Mountain Air",
    price: "$78.10",
    landowner_id: 53,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 34,
    title: "Towering Forest Brimming with Wild Life",
    price: "$285.68",
    landowner_id: 65,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 35,
    title: "Clifftop Views and Rolling Hills",
    price: "$73.40",
    landowner_id: 58,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 36,
    title: "Cabin Escape Just Above the Clouds",
    price: "$59.93",
    landowner_id: 42,
    photo: null,
    amenitites: null,
    address: null,
  },

  {
    id: 37,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$191.49",
    landowner_id: 6,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 38,
    title: "Wilderness Vacation Miles from anyone",
    price: "$63.13",
    landowner_id: 6,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 39,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$141.37",
    landowner_id: 61,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 40,
    title: "Four Wheel Drive Mud Retreat",
    price: "$174.70",
    landowner_id: 69,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 41,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$291.83",
    landowner_id: 86,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 42,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$236.90",
    landowner_id: 3,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 43,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$137.83",
    landowner_id: 58,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 44,
    title: "River Life at its Best",
    price: "$73.72",
    landowner_id: 29,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 45,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$52.34",
    landowner_id: 6,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 46,
    title: "Lake Front Dream Escape",
    price: "$146.33",
    landowner_id: 72,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 47,
    title: "Breathtaking Sunrises",
    price: "$132.37",
    landowner_id: 36,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 48,
    title: "Fresh Mountain Air",
    price: "$282.81",
    landowner_id: 26,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 49,
    title: "Towering Forest Brimming with Wild Life",
    price: "$149.84",
    landowner_id: 82,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 50,
    title: "Clifftop Views and Rolling Hills",
    price: "$183.33",
    landowner_id: 88,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 51,
    title: "Cabin Escape Just Above the Clouds",
    price: "$77.58",
    landowner_id: 80,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 52,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$221.26",
    landowner_id: 8,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 53,
    title: "Wilderness Vacation Miles from anyone",
    price: "$101.28",
    landowner_id: 11,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 54,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$123.55",
    landowner_id: 62,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 55,
    title: "Four Wheel Drive Mud Retreat",
    price: "$195.56",
    landowner_id: 26,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 56,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$122.73",
    landowner_id: 85,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 57,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$63.86",
    landowner_id: 72,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 58,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$113.90",
    landowner_id: 74,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 59,
    title: "River Life at its Best",
    price: "$112.63",
    landowner_id: 4,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 60,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$237.02",
    landowner_id: 47,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 61,
    title: "Lake Front Dream Escape",
    price: "$54.95",
    landowner_id: 68,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 62,
    title: "Breathtaking Sunrises",
    price: "$83.02",
    landowner_id: 98,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 63,
    title: "Fresh Mountain Air",
    price: "$96.00",
    landowner_id: 67,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 64,
    title: "Towering Forest Brimming with Wild Life",
    price: "$102.41",
    landowner_id: 19,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 65,
    title: "Clifftop Views and Rolling Hills",
    price: "$170.65",
    landowner_id: 62,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 66,
    title: "Cabin Escape Just Above the Clouds",
    price: "$113.69",
    landowner_id: 19,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 67,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$137.45",
    landowner_id: 82,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 68,
    title: "Wilderness Vacation Miles from anyone",
    price: "$178.72",
    landowner_id: 86,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 69,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$272.76",
    landowner_id: 91,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 70,
    title: "Four Wheel Drive Mud Retreat",
    price: "$152.02",
    landowner_id: 6,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 71,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$125.34",
    landowner_id: 46,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 72,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$206.78",
    landowner_id: 65,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 73,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$154.36",
    landowner_id: 58,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 74,
    title: "River Life at its Best",
    price: "$248.41",
    landowner_id: 81,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 75,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$129.18",
    landowner_id: 18,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 76,
    title: "Lake Front Dream Escape",
    price: "$168.18",
    landowner_id: 59,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 77,
    title: "Breathtaking Sunrises",
    price: "$110.66",
    landowner_id: 31,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 78,
    title: "Fresh Mountain Air",
    price: "$161.67",
    landowner_id: 84,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 79,
    title: "Towering Forest Brimming with Wild Life",
    price: "$280.72",
    landowner_id: 78,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 80,
    title: "Clifftop Views and Rolling Hills",
    price: "$248.59",
    landowner_id: 76,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 81,
    title: "Cabin Escape Just Above the Clouds",
    price: "$264.59",
    landowner_id: 18,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 82,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$194.69",
    landowner_id: 40,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 83,
    title: "Wilderness Vacation Miles from anyone",
    price: "$50.66",
    landowner_id: 37,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 84,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$292.61",
    landowner_id: 85,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 85,
    title: "Four Wheel Drive Mud Retreat",
    price: "$114.32",
    landowner_id: 97,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 86,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$91.74",
    landowner_id: 100,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 87,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$194.68",
    landowner_id: 79,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 88,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$151.03",
    landowner_id: 37,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 89,
    title: "River Life at its Best",
    price: "$88.63",
    landowner_id: 12,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 90,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$262.29",
    landowner_id: 56,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 91,
    title: "Lake Front Dream Escape",
    price: "$174.31",
    landowner_id: 83,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 92,
    title: "Breathtaking Sunrises",
    price: "$183.75",
    landowner_id: 8,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 93,
    title: "Fresh Mountain Air",
    price: "$176.82",
    landowner_id: 47,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 94,
    title: "Towering Forest Brimming with Wild Life",
    price: "$120.34",
    landowner_id: 95,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 95,
    title: "Clifftop Views and Rolling Hills",
    price: "$76.00",
    landowner_id: 19,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 96,
    title: "Cabin Escape Just Above the Clouds",
    price: "$111.44",
    landowner_id: 85,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 97,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$234.77",
    landowner_id: 96,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 98,
    title: "Wilderness Vacation Miles from anyone",
    price: "$180.67",
    landowner_id: 16,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 99,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$279.14",
    landowner_id: 8,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 100,
    title: "Four Wheel Drive Mud Retreat",
    price: "$290.48",
    landowner_id: 70,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 101,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$102.29",
    landowner_id: 66,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 102,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$201.46",
    landowner_id: 67,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 103,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$67.39",
    landowner_id: 26,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 104,
    title: "River Life at its Best",
    price: "$54.66",
    landowner_id: 61,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 105,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$191.85",
    landowner_id: 8,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 106,
    title: "Lake Front Dream Escape",
    price: "$197.40",
    landowner_id: 79,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 107,
    title: "Breathtaking Sunrises",
    price: "$206.23",
    landowner_id: 13,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 108,
    title: "Fresh Mountain Air",
    price: "$140.85",
    landowner_id: 87,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 109,
    title: "Towering Forest Brimming with Wild Life",
    price: "$110.61",
    landowner_id: 91,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 110,
    title: "Clifftop Views and Rolling Hills",
    price: "$154.35",
    landowner_id: 18,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 111,
    title: "Cabin Escape Just Above the Clouds",
    price: "$230.72",
    landowner_id: 37,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 112,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$199.20",
    landowner_id: 30,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 113,
    title: "Wilderness Vacation Miles from anyone",
    price: "$58.98",
    landowner_id: 27,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 114,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$67.64",
    landowner_id: 14,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 115,
    title: "Four Wheel Drive Mud Retreat",
    price: "$98.26",
    landowner_id: 28,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 116,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$133.04",
    landowner_id: 36,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 117,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$108.11",
    landowner_id: 55,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 118,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$50.36",
    landowner_id: 29,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 119,
    title: "River Life at its Best",
    price: "$234.15",
    landowner_id: 9,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 120,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$224.77",
    landowner_id: 73,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 121,
    title: "Lake Front Dream Escape",
    price: "$160.56",
    landowner_id: 76,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 122,
    title: "Breathtaking Sunrises",
    price: "$208.46",
    landowner_id: 70,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 123,
    title: "Fresh Mountain Air",
    price: "$142.72",
    landowner_id: 20,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 124,
    title: "Towering Forest Brimming with Wild Life",
    price: "$172.87",
    landowner_id: 82,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 125,
    title: "Clifftop Views and Rolling Hills",
    price: "$115.93",
    landowner_id: 88,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 126,
    title: "Cabin Escape Just Above the Clouds",
    price: "$172.40",
    landowner_id: 83,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 127,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$70.17",
    landowner_id: 10,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 128,
    title: "Wilderness Vacation Miles from anyone",
    price: "$73.37",
    landowner_id: 21,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 129,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$162.78",
    landowner_id: 39,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 130,
    title: "Four Wheel Drive Mud Retreat",
    price: "$54.87",
    landowner_id: 19,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 131,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$233.71",
    landowner_id: 27,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 132,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$293.52",
    landowner_id: 30,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 133,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$54.42",
    landowner_id: 89,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 134,
    title: "River Life at its Best",
    price: "$293.24",
    landowner_id: 18,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 135,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$241.07",
    landowner_id: 92,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 136,
    title: "Lake Front Dream Escape",
    price: "$199.23",
    landowner_id: 85,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 137,
    title: "Breathtaking Sunrises",
    price: "$97.06",
    landowner_id: 53,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 138,
    title: "Fresh Mountain Air",
    price: "$190.93",
    landowner_id: 14,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 139,
    title: "Towering Forest Brimming with Wild Life",
    price: "$117.88",
    landowner_id: 65,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 140,
    title: "Clifftop Views and Rolling Hills",
    price: "$140.43",
    landowner_id: 58,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 141,
    title: "Cabin Escape Just Above the Clouds",
    price: "$253.05",
    landowner_id: 71,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 142,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$105.02",
    landowner_id: 37,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 143,
    title: "Wilderness Vacation Miles from anyone",
    price: "$196.70",
    landowner_id: 89,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 144,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$201.53",
    landowner_id: 79,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 145,
    title: "Four Wheel Drive Mud Retreat",
    price: "$76.13",
    landowner_id: 58,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 146,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$200.69",
    landowner_id: 86,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 147,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$223.46",
    landowner_id: 31,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 148,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$96.95",
    landowner_id: 51,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 149,
    title: "River Life at its Best",
    price: "$256.73",
    landowner_id: 98,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 150,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$171.11",
    landowner_id: 99,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 151,
    title: "Lake Front Dream Escape",
    price: "$75.95",
    landowner_id: 15,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 152,
    title: "Breathtaking Sunrises",
    price: "$267.47",
    landowner_id: 100,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 153,
    title: "Fresh Mountain Air",
    price: "$147.88",
    landowner_id: 8,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 154,
    title: "Towering Forest Brimming with Wild Life",
    price: "$176.51",
    landowner_id: 60,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 155,
    title: "Clifftop Views and Rolling Hills",
    price: "$80.38",
    landowner_id: 45,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 156,
    title: "Cabin Escape Just Above the Clouds",
    price: "$261.00",
    landowner_id: 67,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 157,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$241.69",
    landowner_id: 42,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 158,
    title: "Wilderness Vacation Miles from anyone",
    price: "$169.78",
    landowner_id: 17,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 159,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$86.76",
    landowner_id: 85,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 160,
    title: "Four Wheel Drive Mud Retreat",
    price: "$282.65",
    landowner_id: 58,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 161,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$136.82",
    landowner_id: 38,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 162,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$221.56",
    landowner_id: 93,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 163,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$80.10",
    landowner_id: 34,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 164,
    title: "River Life at its Best",
    price: "$243.71",
    landowner_id: 97,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 165,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$128.59",
    landowner_id: 90,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 166,
    title: "Lake Front Dream Escape",
    price: "$64.52",
    landowner_id: 55,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 167,
    title: "Breathtaking Sunrises",
    price: "$111.70",
    landowner_id: 65,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 168,
    title: "Fresh Mountain Air",
    price: "$57.38",
    landowner_id: 81,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 169,
    title: "Towering Forest Brimming with Wild Life",
    price: "$108.82",
    landowner_id: 53,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 170,
    title: "Clifftop Views and Rolling Hills",
    price: "$218.66",
    landowner_id: 71,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 171,
    title: "Cabin Escape Just Above the Clouds",
    price: "$205.37",
    landowner_id: 99,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 172,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$258.75",
    landowner_id: 52,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 173,
    title: "Wilderness Vacation Miles from anyone",
    price: "$83.07",
    landowner_id: 84,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 174,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$241.24",
    landowner_id: 4,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 175,
    title: "Four Wheel Drive Mud Retreat",
    price: "$68.60",
    landowner_id: 26,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 176,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$179.36",
    landowner_id: 3,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 177,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$176.40",
    landowner_id: 17,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 178,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$102.80",
    landowner_id: 79,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 179,
    title: "River Life at its Best",
    price: "$268.54",
    landowner_id: 39,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 180,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$249.66",
    landowner_id: 41,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 181,
    title: "Lake Front Dream Escape",
    price: "$163.87",
    landowner_id: 25,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 182,
    title: "Breathtaking Sunrises",
    price: "$81.15",
    landowner_id: 92,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 183,
    title: "Fresh Mountain Air",
    price: "$281.08",
    landowner_id: 46,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 184,
    title: "Towering Forest Brimming with Wild Life",
    price: "$278.23",
    landowner_id: 87,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 185,
    title: "Clifftop Views and Rolling Hills",
    price: "$262.95",
    landowner_id: 93,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 186,
    title: "Cabin Escape Just Above the Clouds",
    price: "$217.34",
    landowner_id: 88,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 187,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$154.04",
    landowner_id: 94,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 188,
    title: "Wilderness Vacation Miles from anyone",
    price: "$93.56",
    landowner_id: 3,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 189,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$292.38",
    landowner_id: 67,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 190,
    title: "Four Wheel Drive Mud Retreat",
    price: "$271.30",
    landowner_id: 91,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 191,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$204.91",
    landowner_id: 45,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 192,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$124.32",
    landowner_id: 100,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 193,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$184.37",
    landowner_id: 95,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 194,
    title: "River Life at its Best",
    price: "$58.08",
    landowner_id: 54,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 195,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$275.93",
    landowner_id: 85,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 196,
    title: "Lake Front Dream Escape",
    price: "$63.63",
    landowner_id: 38,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 197,
    title: "Breathtaking Sunrises",
    price: "$198.58",
    landowner_id: 6,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 198,
    title: "Fresh Mountain Air",
    price: "$86.98",
    landowner_id: 98,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 199,
    title: "Towering Forest Brimming with Wild Life",
    price: "$245.07",
    landowner_id: 69,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 200,
    title: "Clifftop Views and Rolling Hills",
    price: "$87.32",
    landowner_id: 2,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 201,
    title: "Cabin Escape Just Above the Clouds",
    price: "$183.59",
    landowner_id: 99,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 202,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$272.26",
    landowner_id: 62,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 203,
    title: "Wilderness Vacation Miles from anyone",
    price: "$178.41",
    landowner_id: 14,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 204,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$139.26",
    landowner_id: 17,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 205,
    title: "Four Wheel Drive Mud Retreat",
    price: "$101.50",
    landowner_id: 9,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 206,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$286.55",
    landowner_id: 77,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 207,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$137.99",
    landowner_id: 50,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 208,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$159.14",
    landowner_id: 56,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 209,
    title: "River Life at its Best",
    price: "$126.80",
    landowner_id: 40,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 210,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$291.48",
    landowner_id: 56,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 211,
    title: "Lake Front Dream Escape",
    price: "$109.39",
    landowner_id: 100,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 212,
    title: "Breathtaking Sunrises",
    price: "$259.78",
    landowner_id: 19,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 213,
    title: "Fresh Mountain Air",
    price: "$158.85",
    landowner_id: 56,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 214,
    title: "Towering Forest Brimming with Wild Life",
    price: "$79.22",
    landowner_id: 4,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 215,
    title: "Clifftop Views and Rolling Hills",
    price: "$173.53",
    landowner_id: 15,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 216,
    title: "Cabin Escape Just Above the Clouds",
    price: "$268.30",
    landowner_id: 95,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 217,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$76.09",
    landowner_id: 77,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 218,
    title: "Wilderness Vacation Miles from anyone",
    price: "$199.43",
    landowner_id: 79,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 219,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$56.04",
    landowner_id: 36,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 220,
    title: "Four Wheel Drive Mud Retreat",
    price: "$74.62",
    landowner_id: 10,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 221,
    title:
      "Fresh Grown Fruit and Vegetables Mountain Hikes and Quiet Morning Coffees",
    price: "$279.13",
    landowner_id: 35,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 222,
    title: "Bird Watchers Paradise (Twitchers Welcome)",
    price: "$266.05",
    landowner_id: 83,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 223,
    title: "Wide Open Spaces Super TALL Blue Skies Fresh Air",
    price: "$158.07",
    landowner_id: 66,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 224,
    title: "River Life at its Best",
    price: "$173.25",
    landowner_id: 98,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 225,
    title: "Whitewater Rapids Fresh Morning Brew",
    price: "$279.73",
    landowner_id: 78,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 226,
    title: "Lake Front Dream Escape",
    price: "$91.71",
    landowner_id: 84,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 227,
    title: "Breathtaking Sunrises",
    price: "$75.30",
    landowner_id: 40,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 228,
    title: "Fresh Mountain Air",
    price: "$126.11",
    landowner_id: 96,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 229,
    title: "Towering Forest Brimming with Wild Life",
    price: "$276.50",
    landowner_id: 21,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 230,
    title: "Clifftop Views and Rolling Hills",
    price: "$199.10",
    landowner_id: 2,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 231,
    title: "Cabin Escape Just Above the Clouds",
    price: "$181.52",
    landowner_id: 39,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 232,
    title: "Wooded Wonderland Minutes from the Metro",
    price: "$265.44",
    landowner_id: 35,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 233,
    title: "Wilderness Vacation Miles from anyone",
    price: "$240.03",
    landowner_id: 64,
    photo: null,
    amenitites: null,
    address: null,
  },
  {
    id: 234,
    title: "Surfing Sand Dunes and Soaking up Sun Rays",
    price: "$88.52",
    landowner_id: 48,
    photo: null,
    amenitites: null,
    address: null,
  },
];

const addy2020 = [
  {
    address: "777 Brockton Avenue",
    city: "Abington",
    state: "MA",
    zip: "2351",
  },
  { address: "30 Memorial Drive", city: "Avon", state: "MA", zip: "2322" },
  {
    address: "250 Hartford Avenue",
    city: "Bellingham",
    state: "MA",
    zip: "2019",
  },
  { address: "700 Oak Street", city: "Brockton", state: "MA", zip: "2301" },
  {
    address: "66-4 Parkhurst Rd",
    city: "Chelmsford",
    state: "MA",
    zip: "1824",
  },
  { address: "591 Memorial Dr", city: "Chicopee", state: "MA", zip: "1020" },
  {
    address: "55 Brooksby Village Way",
    city: "Danvers",
    state: "MA",
    zip: "1923",
  },
  {
    address: "137 Teaticket Hwy",
    city: "East Falmouth",
    state: "MA",
    zip: "2536",
  },
  {
    address: "42 Fairhaven Commons Way",
    city: "Fairhaven",
    state: "MA",
    zip: "2719",
  },
  {
    address: "374 William S Canning Blvd",
    city: "Fall River",
    state: "MA",
    zip: "2721",
  },
  { address: "121 Worcester Rd", city: "Framingham", state: "MA", zip: "1701" },
  { address: "677 Timpany Blvd", city: "Gardner", state: "MA", zip: "1440" },
  { address: "337 Russell St", city: "Hadley", state: "MA", zip: "1035" },
  { address: "295 Plymouth Street", city: "Halifax", state: "MA", zip: "2338" },
  { address: "1775 Washington St", city: "Hanover", state: "MA", zip: "2339" },
  {
    address: "280 Washington Street",
    city: "Hudson",
    state: "MA",
    zip: "1749",
  },
  { address: "20 Soojian Dr", city: "Leicester", state: "MA", zip: "1524" },
  { address: "11 Jungle Road", city: "Leominster", state: "MA", zip: "1453" },
  {
    address: "301 Massachusetts Ave",
    city: "Lunenburg",
    state: "MA",
    zip: "1462",
  },
  { address: "780 Lynnway", city: "Lynn", state: "MA", zip: "1905" },
  {
    address: "70 Pleasant Valley Street",
    city: "Methuen",
    state: "MA",
    zip: "1844",
  },
  {
    address: "830 Curran Memorial Hwy",
    city: "North Adams",
    state: "MA",
    zip: "1247",
  },
  {
    address: "1470 S Washington St",
    city: "North Attleboro",
    state: "MA",
    zip: "2760",
  },
  {
    address: "506 State Road",
    city: "North Dartmouth",
    state: "MA",
    zip: "2747",
  },
  {
    address: "742 Main Street",
    city: "North Oxford",
    state: "MA",
    zip: "1537",
  },
  { address: "72 Main St", city: "North Reading", state: "MA", zip: "1864" },
  {
    address: "200 Otis Street",
    city: "Northborough",
    state: "MA",
    zip: "1532",
  },
  {
    address: "180 North King Street",
    city: "Northhampton",
    state: "MA",
    zip: "1060",
  },
  { address: "555 East Main St", city: "Orange", state: "MA", zip: "1364" },
  {
    address: "555 Hubbard Ave-Suite 12",
    city: "Pittsfield",
    state: "MA",
    zip: "1201",
  },
  { address: "300 Colony Place", city: "Plymouth", state: "MA", zip: "2360" },
  { address: "301 Falls Blvd", city: "Quincy", state: "MA", zip: "2169" },
  { address: "36 Paramount Drive", city: "Raynham", state: "MA", zip: "2767" },
  { address: "450 Highland Ave", city: "Salem", state: "MA", zip: "1970" },
  {
    address: "1180 Fall River Avenue",
    city: "Seekonk",
    state: "MA",
    zip: "2771",
  },
  {
    address: "1105 Boston Road",
    city: "Springfield",
    state: "MA",
    zip: "1119",
  },
  {
    address: "100 Charlton Road",
    city: "Sturbridge",
    state: "MA",
    zip: "1566",
  },
  { address: "262 Swansea Mall Dr", city: "Swansea", state: "MA", zip: "2777" },
  { address: "333 Main Street", city: "Tewksbury", state: "MA", zip: "1876" },
  { address: "550 Providence Hwy", city: "Walpole", state: "MA", zip: "2081" },
  { address: "352 Palmer Road", city: "Ware", state: "MA", zip: "1082" },
  {
    address: "3005 Cranberry Hwy Rt 6 28",
    city: "Wareham",
    state: "MA",
    zip: "2538",
  },
  { address: "250 Rt 59", city: "Airmont", state: "NY", zip: "10901" },
  {
    address: "141 Washington Ave Extension",
    city: "Albany",
    state: "NY",
    zip: "12205",
  },
  { address: "13858 Rt 31 W", city: "Albion", state: "NY", zip: "14411" },
  {
    address: "2055 Niagara Falls Blvd",
    city: "Amherst",
    state: "NY",
    zip: "14228",
  },
  {
    address: "101 Sanford Farm Shpg Center",
    city: "Amsterdam",
    state: "NY",
    zip: "12010",
  },
  { address: "297 Grant Avenue", city: "Auburn", state: "NY", zip: "13021" },
  {
    address: "4133 Veterans Memorial Drive",
    city: "Batavia",
    state: "NY",
    zip: "14020",
  },
  {
    address: "6265 Brockport Spencerport Rd",
    city: "Brockport",
    state: "NY",
    zip: "14420",
  },
  { address: "5399 W Genesse St", city: "Camillus", state: "NY", zip: "13031" },
  {
    address: "3191 County rd 10",
    city: "Canandaigua",
    state: "NY",
    zip: "14424",
  },
  { address: "30 Catskill", city: "Catskill", state: "NY", zip: "12414" },
  {
    address: "161 Centereach Mall",
    city: "Centereach",
    state: "NY",
    zip: "11720",
  },
  {
    address: "3018 East Ave",
    city: "Central Square",
    state: "NY",
    zip: "13036",
  },
  {
    address: "100 Thruway Plaza",
    city: "Cheektowaga",
    state: "NY",
    zip: "14225",
  },
  { address: "8064 Brewerton Rd", city: "Cicero", state: "NY", zip: "13039" },
  { address: "5033 Transit Road", city: "Clarence", state: "NY", zip: "14031" },
  { address: "3949 Route 31", city: "Clay", state: "NY", zip: "13041" },
  {
    address: "139 Merchant Place",
    city: "Cobleskill",
    state: "NY",
    zip: "12043",
  },
  {
    address: "85 Crooked Hill Road",
    city: "Commack",
    state: "NY",
    zip: "11725",
  },
  { address: "872 Route 13", city: "Cortlandville", state: "NY", zip: "13045" },
  {
    address: "279 Troy Road",
    city: "East Greenbush",
    state: "NY",
    zip: "12061",
  },
  {
    address: "2465 Hempstead Turnpike",
    city: "East Meadow",
    state: "NY",
    zip: "11554",
  },
  {
    address: "6438 Basile Rowe",
    city: "East Syracuse",
    state: "NY",
    zip: "13057",
  },
  { address: "25737 US Rt 11", city: "Evans Mills", state: "NY", zip: "13637" },
  { address: "901 Route 110", city: "Farmingdale", state: "NY", zip: "11735" },
  { address: "2400 Route 9", city: "Fishkill", state: "NY", zip: "12524" },
  {
    address: "10401 Bennett Road",
    city: "Fredonia",
    state: "NY",
    zip: "14063",
  },
  { address: "1818 State Route 3", city: "Fulton", state: "NY", zip: "13069" },
  {
    address: "4300 Lakeville Road",
    city: "Geneseo",
    state: "NY",
    zip: "14454",
  },
  { address: "990 Route 5 20", city: "Geneva", state: "NY", zip: "14456" },
  { address: "311 RT 9W", city: "Glenmont", state: "NY", zip: "12077" },
  {
    address: "200 Dutch Meadows Ln",
    city: "Glenville",
    state: "NY",
    zip: "12302",
  },
  {
    address: "100 Elm Ridge Center Dr",
    city: "Greece",
    state: "NY",
    zip: "14626",
  },
  { address: "1549 Rt 9", city: "Halfmoon", state: "NY", zip: "12065" },
  {
    address: "5360 Southwestern Blvd",
    city: "Hamburg",
    state: "NY",
    zip: "14075",
  },
  {
    address: "103 North Caroline St",
    city: "Herkimer",
    state: "NY",
    zip: "13350",
  },
  {
    address: "1000 State Route 36",
    city: "Hornell",
    state: "NY",
    zip: "14843",
  },
  {
    address: "1400 County Rd 64",
    city: "Horseheads",
    state: "NY",
    zip: "14845",
  },
  {
    address: "135 Fairgrounds Memorial Pkwy",
    city: "Ithaca",
    state: "NY",
    zip: "14850",
  },
  { address: "2 Gannett Dr", city: "Johnson City", state: "NY", zip: "13790" },
  { address: "233 5th Ave Ext", city: "Johnstown", state: "NY", zip: "12095" },
  {
    address: "601 Frank Stottile Blvd",
    city: "Kingston",
    state: "NY",
    zip: "12401",
  },
  {
    address: "350 E Fairmount Ave",
    city: "Lakewood",
    state: "NY",
    zip: "14750",
  },
  { address: "4975 Transit Rd", city: "Lancaster", state: "NY", zip: "14086" },
  {
    address: "579 Troy-Schenectady Road",
    city: "Latham",
    state: "NY",
    zip: "12110",
  },
  {
    address: "5783 So Transit Road",
    city: "Lockport",
    state: "NY",
    zip: "14094",
  },
  {
    address: "7155 State Rt 12 S",
    city: "Lowville",
    state: "NY",
    zip: "13367",
  },
  { address: "425 Route 31", city: "Macedon", state: "NY", zip: "14502" },
  { address: "3222 State Rt 11", city: "Malone", state: "NY", zip: "12953" },
  {
    address: "200 Sunrise Mall",
    city: "Massapequa",
    state: "NY",
    zip: "11758",
  },
  { address: "43 Stephenville St", city: "Massena", state: "NY", zip: "13662" },
  {
    address: "750 Middle Country Road",
    city: "Middle Island",
    state: "NY",
    zip: "11953",
  },
  {
    address: "470 Route 211 East",
    city: "Middletown",
    state: "NY",
    zip: "10940",
  },
  {
    address: "3133 E Main St",
    city: "Mohegan Lake",
    state: "NY",
    zip: "10547",
  },
  { address: "288 Larkin", city: "Monroe", state: "NY", zip: "10950" },
  {
    address: "41 Anawana Lake Road",
    city: "Monticello",
    state: "NY",
    zip: "12701",
  },
  {
    address: "4765 Commercial Drive",
    city: "New Hartford",
    state: "NY",
    zip: "13413",
  },
  { address: "1201 Rt 300", city: "Newburgh", state: "NY", zip: "12550" },
  { address: "255 W Main St", city: "Avon", state: "CT", zip: "6001" },
  {
    address: "120 Commercial Parkway",
    city: "Branford",
    state: "CT",
    zip: "6405",
  },
  { address: "1400 Farmington Ave", city: "Bristol", state: "CT", zip: "6010" },
  { address: "161 Berlin Road", city: "Cromwell", state: "CT", zip: "6416" },
  { address: "67 Newton Rd", city: "Danbury", state: "CT", zip: "6810" },
  { address: "656 New Haven Ave", city: "Derby", state: "CT", zip: "6418" },
  {
    address: "69 Prospect Hill Road",
    city: "East Windsor",
    state: "CT",
    zip: "6088",
  },
  { address: "150 Gold Star Hwy", city: "Groton", state: "CT", zip: "6340" },
  {
    address: "900 Boston Post Road",
    city: "Guilford",
    state: "CT",
    zip: "6437",
  },
  { address: "2300 Dixwell Ave", city: "Hamden", state: "CT", zip: "6514" },
  { address: "495 Flatbush Ave", city: "Hartford", state: "CT", zip: "6106" },
  { address: "180 River Rd", city: "Lisbon", state: "CT", zip: "6351" },
  {
    address: "420 Buckland Hills Dr",
    city: "Manchester",
    state: "CT",
    zip: "6040",
  },
  {
    address: "1365 Boston Post Road",
    city: "Milford",
    state: "CT",
    zip: "6460",
  },
  {
    address: "1100 New Haven Road",
    city: "Naugatuck",
    state: "CT",
    zip: "6770",
  },
  { address: "315 Foxon Blvd", city: "New Haven", state: "CT", zip: "6513" },
  { address: "164 Danbury Rd", city: "New Milford", state: "CT", zip: "6776" },
  {
    address: "3164 Berlin Turnpike",
    city: "Newington",
    state: "CT",
    zip: "6111",
  },
  {
    address: "474 Boston Post Road",
    city: "North Windham",
    state: "CT",
    zip: "6256",
  },
  { address: "650 Main Ave", city: "Norwalk", state: "CT", zip: "6851" },
  {
    address: "680 Connecticut Avenue",
    city: "Norwalk",
    state: "CT",
    zip: "6854",
  },
  { address: "220 Salem Turnpike", city: "Norwich", state: "CT", zip: "6360" },
  {
    address: "655 Boston Post Rd",
    city: "Old Saybrook",
    state: "CT",
    zip: "6475",
  },
  { address: "625 School Street", city: "Putnam", state: "CT", zip: "6260" },
  { address: "80 Town Line Rd", city: "Rocky Hill", state: "CT", zip: "6067" },
  {
    address: "465 Bridgeport Avenue",
    city: "Shelton",
    state: "CT",
    zip: "6484",
  },
  { address: "235 Queen St", city: "Southington", state: "CT", zip: "6489" },
  {
    address: "150 Barnum Avenue Cutoff",
    city: "Stratford",
    state: "CT",
    zip: "6614",
  },
  {
    address: "970 Torringford Street",
    city: "Torrington",
    state: "CT",
    zip: "6790",
  },
  {
    address: "844 No Colony Road",
    city: "Wallingford",
    state: "CT",
    zip: "6492",
  },
  { address: "910 Wolcott St", city: "Waterbury", state: "CT", zip: "6705" },
  {
    address: "155 Waterford Parkway No",
    city: "Waterford",
    state: "CT",
    zip: "6385",
  },
  { address: "515 Sawmill Road", city: "West Haven", state: "CT", zip: "6516" },
  {
    address: "2473 Hackworth Road",
    city: "Adamsville",
    state: "AL",
    zip: "35005",
  },
  {
    address: "630 Coonial Promenade Pkwy",
    city: "Alabaster",
    state: "AL",
    zip: "35007",
  },
  {
    address: "2643 Hwy 280 West",
    city: "Alexander City",
    state: "AL",
    zip: "35010",
  },
  { address: "540 West Bypass", city: "Andalusia", state: "AL", zip: "36420" },
  {
    address: "5560 Mcclellan Blvd",
    city: "Anniston",
    state: "AL",
    zip: "36206",
  },
  {
    address: "1450 No Brindlee Mtn Pkwy",
    city: "Arab",
    state: "AL",
    zip: "35016",
  },
  { address: "1011 US Hwy 72 East", city: "Athens", state: "AL", zip: "35611" },
  {
    address: "973 Gilbert Ferry Road Se",
    city: "Attalla",
    state: "AL",
    zip: "35954",
  },
  {
    address: "1717 South College Street",
    city: "Auburn",
    state: "AL",
    zip: "36830",
  },
  {
    address: "701 Mcmeans Ave",
    city: "Bay Minette",
    state: "AL",
    zip: "36507",
  },
  { address: "750 Academy Drive", city: "Bessemer", state: "AL", zip: "35022" },
  {
    address: "312 Palisades Blvd",
    city: "Birmingham",
    state: "AL",
    zip: "35209",
  },
  {
    address: "1600 Montclair Rd",
    city: "Birmingham",
    state: "AL",
    zip: "35210",
  },
  {
    address: "5919 Trussville Crossings Pkwy",
    city: "Birmingham",
    state: "AL",
    zip: "35235",
  },
  {
    address: "9248 Parkway East",
    city: "Birmingham",
    state: "AL",
    zip: "35206",
  },
  { address: "1972 Hwy 431", city: "Boaz", state: "AL", zip: "35957" },
  { address: "10675 Hwy 5", city: "Brent", state: "AL", zip: "35034" },
  {
    address: "2041 Douglas Avenue",
    city: "Brewton",
    state: "AL",
    zip: "36426",
  },
  { address: "5100 Hwy 31", city: "Calera", state: "AL", zip: "35040" },
  {
    address: "1916 Center Point Rd",
    city: "Center Point",
    state: "AL",
    zip: "35215",
  },
  { address: "1950 W Main St", city: "Centre", state: "AL", zip: "35960" },
  { address: "16077 Highway 280", city: "Chelsea", state: "AL", zip: "35043" },
  {
    address: "1415 7Th Street South",
    city: "Clanton",
    state: "AL",
    zip: "35045",
  },
  {
    address: "626 Olive Street Sw",
    city: "Cullman",
    state: "AL",
    zip: "35055",
  },
  { address: "27520 Hwy 98", city: "Daphne", state: "AL", zip: "36526" },
  { address: "2800 Spring Avn SW", city: "Decatur", state: "AL", zip: "35603" },
  {
    address: "969 Us Hwy 80 West",
    city: "Demopolis",
    state: "AL",
    zip: "36732",
  },
  {
    address: "3300 South Oates Street",
    city: "Dothan",
    state: "AL",
    zip: "36301",
  },
  { address: "4310 Montgomery Hwy", city: "Dothan", state: "AL", zip: "36303" },
  {
    address: "600 Boll Weevil Circle",
    city: "Enterprise",
    state: "AL",
    zip: "36330",
  },
  {
    address: "3176 South Eufaula Avenue",
    city: "Eufaula",
    state: "AL",
    zip: "36027",
  },
  {
    address: "7100 Aaron Aronov Drive",
    city: "Fairfield",
    state: "AL",
    zip: "35064",
  },
  {
    address: "10040 County Road 48",
    city: "Fairhope",
    state: "AL",
    zip: "36533",
  },
  { address: "3186 Hwy 171 North", city: "Fayette", state: "AL", zip: "35555" },
  { address: "3100 Hough Rd", city: "Florence", state: "AL", zip: "35630" },
  {
    address: "2200 South Mckenzie St",
    city: "Foley",
    state: "AL",
    zip: "36535",
  },
  {
    address: "2001 Glenn Bldv Sw",
    city: "Fort Payne",
    state: "AL",
    zip: "35968",
  },
  {
    address: "340 East Meighan Blvd",
    city: "Gadsden",
    state: "AL",
    zip: "35903",
  },
  { address: "890 Odum Road", city: "Gardendale", state: "AL", zip: "35071" },
  { address: "1608 W Magnolia Ave", city: "Geneva", state: "AL", zip: "36340" },
  { address: "501 Willow Lane", city: "Greenville", state: "AL", zip: "36037" },
  {
    address: "170 Fort Morgan Road",
    city: "Gulf Shores",
    state: "AL",
    zip: "36542",
  },
  {
    address: "11697 US Hwy 431",
    city: "Guntersville",
    state: "AL",
    zip: "35976",
  },
  { address: "42417 Hwy 195", city: "Haleyville", state: "AL", zip: "35565" },
  {
    address: "1706 Military Street South",
    city: "Hamilton",
    state: "AL",
    zip: "35570",
  },
  { address: "1201 Hwy 31 NW", city: "Hartselle", state: "AL", zip: "35640" },
  {
    address: "209 Lakeshore Parkway",
    city: "Homewood",
    state: "AL",
    zip: "35209",
  },
  {
    address: "2780 John Hawkins Pkwy",
    city: "Hoover",
    state: "AL",
    zip: "35244",
  },
  { address: "5335 Hwy 280 South", city: "Hoover", state: "AL", zip: "35242" },
  {
    address: "1007 Red Farmer Drive",
    city: "Hueytown",
    state: "AL",
    zip: "35023",
  },
  {
    address: "2900 S Mem PkwyDrake Ave",
    city: "Huntsville",
    state: "AL",
    zip: "35801",
  },
  {
    address: "11610 Memorial Pkwy South",
    city: "Huntsville",
    state: "AL",
    zip: "35803",
  },
  {
    address: "2200 Sparkman Drive",
    city: "Huntsville",
    state: "AL",
    zip: "35810",
  },
  { address: "330 Sutton Rd", city: "Huntsville", state: "AL", zip: "35763" },
  {
    address: "6140A Univ Drive",
    city: "Huntsville",
    state: "AL",
    zip: "35806",
  },
  { address: "4206 N College Ave", city: "Jackson", state: "AL", zip: "36545" },
  {
    address: "1625 Pelham South",
    city: "Jacksonville",
    state: "AL",
    zip: "36265",
  },
  { address: "1801 Hwy 78 East", city: "Jasper", state: "AL", zip: "35501" },
  { address: "8551 Whitfield Ave", city: "Leeds", state: "AL", zip: "35094" },
  { address: "8650 Madison Blvd", city: "Madison", state: "AL", zip: "35758" },
  { address: "145 Kelley Blvd", city: "Millbrook", state: "AL", zip: "36054" },
  {
    address: "1970 S University Blvd",
    city: "Mobile",
    state: "AL",
    zip: "36609",
  },
  {
    address: "6350 Cottage Hill Road",
    city: "Mobile",
    state: "AL",
    zip: "36609",
  },
  {
    address: "101 South Beltline Highway",
    city: "Mobile",
    state: "AL",
    zip: "36606",
  },
  { address: "2500 Dawes Road", city: "Mobile", state: "AL", zip: "36695" },
  {
    address: "5245 Rangeline Service Rd",
    city: "Mobile",
    state: "AL",
    zip: "36619",
  },
  { address: "685 Schillinger Rd", city: "Mobile", state: "AL", zip: "36695" },
  {
    address: "3371 S Alabama Ave",
    city: "Monroeville",
    state: "AL",
    zip: "36460",
  },
  {
    address: "10710 Chantilly Pkwy",
    city: "Montgomery",
    state: "AL",
    zip: "36117",
  },
  {
    address: "3801 Eastern Blvd",
    city: "Montgomery",
    state: "AL",
    zip: "36116",
  },
  {
    address: "6495 Atlanta Hwy",
    city: "Montgomery",
    state: "AL",
    zip: "36117",
  },
  { address: "851 Ann St", city: "Montgomery", state: "AL", zip: "36107" },
  { address: "15445 Highway 24", city: "Moulton", state: "AL", zip: "35650" },
  {
    address: "517 West Avalon Ave",
    city: "Muscle Shoals",
    state: "AL",
    zip: "35661",
  },
  {
    address: "5710 Mcfarland Blvd",
    city: "Northport",
    state: "AL",
    zip: "35476",
  },
  {
    address: "2453 2Nd Avenue East",
    city: "Oneonta",
    state: "AL",
    zip: "35121",
  },
  {
    address: "2900 Pepperrell Pkwy",
    city: "Opelika",
    state: "AL",
    zip: "36801",
  },
  { address: "92 Plaza Lane", city: "Oxford", state: "AL", zip: "36203" },
  { address: "1537 Hwy 231 South", city: "Ozark", state: "AL", zip: "36360" },
  { address: "2181 Pelham Pkwy", city: "Pelham", state: "AL", zip: "35124" },
  { address: "165 Vaughan Ln", city: "Pell City", state: "AL", zip: "35125" },
  {
    address: "3700 Hwy 280-431 N",
    city: "Phenix City",
    state: "AL",
    zip: "36867",
  },
  {
    address: "1903 Cobbs Ford Rd",
    city: "Prattville",
    state: "AL",
    zip: "36066",
  },
  { address: "4180 Us Hwy 431", city: "Roanoke", state: "AL", zip: "36274" },
  { address: "13675 Hwy 43", city: "Russellville", state: "AL", zip: "35653" },
  {
    address: "1095 Industrial Pkwy",
    city: "Saraland",
    state: "AL",
    zip: "36571",
  },
  {
    address: "24833 Johnt Reidprkw",
    city: "Scottsboro",
    state: "AL",
    zip: "35768",
  },
  { address: "1501 Hwy 14 East", city: "Selma", state: "AL", zip: "36703" },
  { address: "7855 Moffett Rd", city: "Semmes", state: "AL", zip: "36575" },
  {
    address: "150 Springville Station Blvd",
    city: "Springville",
    state: "AL",
    zip: "35146",
  },
  { address: "690 Hwy 78", city: "Sumiton", state: "AL", zip: "35148" },
  { address: "41301 US Hwy 280", city: "Sylacauga", state: "AL", zip: "35150" },
  {
    address: "214 Haynes Street",
    city: "Talladega",
    state: "AL",
    zip: "35160",
  },
  { address: "1300 Gilmer Ave", city: "Tallassee", state: "AL", zip: "36078" },
  { address: "34301 Hwy 43", city: "Thomasville", state: "AL", zip: "36784" },
  { address: "1420 Us 231 South", city: "Troy", state: "AL", zip: "36081" },
  {
    address: "1501 Skyland Blvd E",
    city: "Tuscaloosa",
    state: "AL",
    zip: "35405",
  },
  { address: "3501 20th Av", city: "Valley", state: "AL", zip: "36854" },
  {
    address: "1300 Montgomery Highway",
    city: "Vestavia Hills",
    state: "AL",
    zip: "35216",
  },
  { address: "4538 Us Hwy 231", city: "Wetumpka", state: "AL", zip: "36092" },
  { address: "2575 Us Hwy 43", city: "Winfield", state: "AL", zip: "35594" },
];

const new_amenities = [
  {
    guests: 5,
    beds: 4,
    bath: 3,
    wifi: true,
    kitchen: false,
    heat: true,
    water: true,
    shower: true,
    firepit: false,
  },
  {
    guests: 14,
    beds: 8,
    bath: 1,
    wifi: false,
    kitchen: true,
    heat: true,
    water: false,
    shower: true,
    firepit: true,
  },
  {
    guests: 3,
    beds: 3,
    bath: 1,
    wifi: false,
    kitchen: false,
    heat: true,
    water: true,
    shower: false,
    firepit: false,
  },
  {
    guests: 5,
    beds: 3,
    bath: 2,
    wifi: true,
    kitchen: false,
    heat: true,
    water: false,
    shower: true,
    firepit: false,
  },
  {
    guests: 10,
    beds: 7,
    bath: 2,
    wifi: false,
    kitchen: true,
    heat: true,
    water: false,
    shower: true,
    firepit: true,
  },
  {
    guests: 6,
    beds: 3,
    bath: 3,
    wifi: true,
    kitchen: true,
    heat: true,
    water: true,
    shower: true,
    firepit: false,
  },
  {
    guests: 3,
    beds: 2,
    bath: 1,
    wifi: false,
    kitchen: true,
    heat: false,
    water: true,
    shower: true,
    firepit: false,
  },
  {
    guests: 4,
    beds: 4,
    bath: 2,
    wifi: true,
    kitchen: true,
    heat: true,
    water: true,
    shower: true,
    firepit: false,
  },
  {
    guests: 12,
    beds: 5,
    bath: 3,
    wifi: false,
    kitchen: false,
    heat: false,
    water: true,
    shower: true,
    firepit: false,
  },
  {
    guests: 7,
    beds: 7,
    bath: 2,
    wifi: false,
    kitchen: true,
    heat: true,
    water: true,
    shower: true,
    firepit: true,
  },
  {
    guests: 14,
    beds: 7,
    bath: 3,
    wifi: true,
    kitchen: false,
    heat: false,
    water: false,
    shower: true,
    firepit: false,
  },
  {
    guests: 12,
    beds: 2,
    bath: 1,
    wifi: true,
    kitchen: true,
    heat: false,
    water: true,
    shower: false,
    firepit: true,
  },
  {
    guests: 15,
    beds: 11,
    bath: 3,
    wifi: false,
    kitchen: true,
    heat: true,
    water: true,
    shower: false,
    firepit: false,
  },
  {
    guests: 8,
    beds: 7,
    bath: 1,
    wifi: false,
    kitchen: false,
    heat: true,
    water: true,
    shower: true,
    firepit: true,
  },
  {
    guests: 7,
    beds: 6,
    bath: 2,
    wifi: false,
    kitchen: true,
    heat: false,
    water: true,
    shower: false,
    firepit: false,
  },
  {
    guests: 3,
    beds: 2,
    bath: 3,
    wifi: true,
    kitchen: true,
    heat: true,
    water: true,
    shower: false,
    firepit: false,
  },
  {
    guests: 4,
    beds: 4,
    bath: 2,
    wifi: true,
    kitchen: false,
    heat: true,
    water: true,
    shower: false,
    firepit: false,
  },
  {
    guests: 15,
    beds: 9,
    bath: 3,
    wifi: true,
    kitchen: true,
    heat: false,
    water: true,
    shower: true,
    firepit: false,
  },
  {
    guests: 7,
    beds: 3,
    bath: 3,
    wifi: false,
    kitchen: false,
    heat: true,
    water: true,
    shower: true,
    firepit: false,
  },
  {
    guests: 14,
    beds: 12,
    bath: 3,
    wifi: false,
    kitchen: true,
    heat: false,
    water: true,
    shower: false,
    firepit: false,
  },
  {
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: false,
    kitchen: true,
    heat: true,
    water: false,
    shower: false,
    firepit: false,
  },
  {
    guests: 10,
    beds: 2,
    bath: 1,
    wifi: true,
    kitchen: true,
    heat: false,
    water: true,
    shower: true,
    firepit: true,
  },
  {
    guests: 6,
    beds: 5,
    bath: 2,
    wifi: true,
    kitchen: false,
    heat: true,
    water: true,
    shower: false,
    firepit: false,
  },
  {
    guests: 7,
    beds: 2,
    bath: 2,
    wifi: false,
    kitchen: true,
    heat: true,
    water: false,
    shower: false,
    firepit: true,
  },
  {
    guests: 7,
    beds: 6,
    bath: 3,
    wifi: false,
    kitchen: false,
    heat: true,
    water: true,
    shower: false,
    firepit: true,
  },
];

let newListings = [];

// for (let listing of listings2020) {
//   let newListing = { ...listing, amenities: { ...new_amenities[listing.id] } };
//   newListings.push(newListing);
// }

let finalListings = [];
let i=0
// for (let listing of listings2020) {

// if(i===25&&listing.id<237){i=0}

//     let newListing = {
//       ...listing,
//       address: { ...addy2020[listing.id] },
//       amenities: { ...new_amenities[i] },
//     };
//     finalListings.push(newListing);
//     i++
// }

let rlistings=[]

for (let listing of listings2020){
  
  let newListing = {
    ...listing,
      address: { ...addy2020[listing.id] },}
      //       amenities: { ...new_amenities[i] },
      //     };
    finalListings.push(newListing);
    //     i++
  }
  console.log({finalListings})
  for (let listing of finalListings){
    let i= Math.floor(Math.random()*26)
    let newListing={
    ...listing,
    amenities:{...new_amenities[i]}
  }
  rlistings.push(newListing)
}
console.log({rlistings})

  export default rlistings;